services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: "chave_super_secreta_de_producao"
      DATABASE_URL: "file:///app/data/nome_do_banco.db"
    volumes:
      # Isola o arquivo .db em um volume persistente para não perder dados ao reiniciar
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:4000/graphql
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data: